name: BJFilmProduction
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100607'
    - '#ffffff'
    - '#9c9396'
    - '#f09624'
    - '#c7ccc8'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
