name: BJFilmProduction
favicon: null
layout_spectrum: 0.90504827699624
typography_spectrum: 0.06102896435186267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2689423277042806
  lightness: 0.28741715964861214
  saturation: 0.0010832666885107756
  rhythmicContrast: 0.5978095296304673
purpose: []
